Updated Access Modal to not go back to the access list
ucdavis/Peaks pull request #1007
Opened 2020-09-04 22:22 UTC by wongband

closes #995

2020-09-08 17:50 UTC, srkirkland commented on Keas.Mvc/ClientApp/components/Access/AccessDetails.tsx
> +  const [shouldOpenEditModal, setEditModal] = useState<boolean>(false);
as a convention the useState should be `variableName` and `setVariableName` so it forms an easy to find pair. In this example that would mean naming them `const [shouldOpenEditModal, setShouldOpenEditModal]`

2020-09-08 17:50 UTC, srkirkland approved these changes
Otherwise maybe wait for Jason to take a look functionally tomorrow but the rest looks good to me and I like the move to hooks too

2020-09-09 19:57 UTC, jSylvestre requested changes
I'm getting an error assigning access.
I'll try to debug into it....

2020-09-09 20:01 UTC, wongband commented
@jSylvestre what bug are you getting?

2020-09-09 20:07 UTC, jSylvestre commented
> @jSylvestre what bug are you getting?

@wongband It is happening here:
https://github.com/ucdavis/Peaks/blob/master/Keas.Mvc/Controllers/Api/AccessController.cs#L159

2020-09-09 20:38 UTC, jSylvestre approved these changes
I'll merge once all the checks finish

2020-09-09 21:52 UTC, merged