Converted more sub components from Equipment to use hooks
ucdavis/Peaks pull request #1022
Opened 2020-09-17 21:01 UTC by wongband

Converted the following components:
- EditEquipment
- DeleteEquipment
- EquipmentAttribute
- EquipmentAttributes
- EquipmentBigFix
- EquipmentBigFixInfo
- EquipmentBigFixSearchId

2020-09-17 22:20 UTC, srkirkland requested changes

2020-09-17 22:20 UTC, srkirkland commented on Keas.Mvc/ClientApp/components/Equipment/EquipmentAttribute.tsx
> +  // export default class EquipmentAttribute extends React.Component<IProps, {}> {
dump this comment

2020-09-17 22:20 UTC, srkirkland commented on Keas.Mvc/ClientApp/components/Equipment/EquipmentBigFixSearchId.tsx
> +  // export default class EquipmentBigFixSearchId extends React.Component<
🗑️

2020-09-17 22:30 UTC, srkirkland approved these changes

2020-09-18 18:32 UTC, jSylvestre approved these changes

2020-09-18 18:33 UTC, merged