Updated some Container components to use hooks
ucdavis/Peaks pull request #1035
Opened 2020-09-24 21:09 UTC by wongband

Converted the following:
- SpacesContainer
- EquipmentContainer

To dos:
- Fix details test for each container

2020-09-30 16:19 UTC, jSylvestre requested changes
From person page.
Add a new equipment. Either create a new one or pick an existing.
Go.

Page is blank:
![image](https://user-images.githubusercontent.com/469010/94712213-042def00-02fe-11eb-93ba-62d2ca8c2979.png)

2020-10-01 17:29 UTC, wongband commented
@jSylvestre fixed the bug in this push ^^

2020-10-01 19:20 UTC, jSylvestre requested changes
From within a person, try to assign an existing access fails.
Creating and assigning a new access seems to work fine.

![image](https://user-images.githubusercontent.com/469010/94853623-8393ef00-03e0-11eb-8e6a-43b12688e451.png)

2020-10-01 21:15 UTC, srkirkland requested changes

2020-10-01 21:15 UTC, srkirkland commented on Keas.Mvc/ClientApp/components/People/PeopleContainer.tsx
> +interface IParams {
You don't need this, use IMatchParams

2020-10-01 21:15 UTC, srkirkland commented on Keas.Mvc/ClientApp/components/Spaces/SpacesContainer.tsx
> +interface IParams {
delete and use imatchparams

2020-10-01 21:21 UTC, srkirkland approved these changes

2020-10-02 15:45 UTC, jSylvestre approved these changes

2020-10-02 16:05 UTC, merged